# Generated by Django 4.2.17 on 2026-03-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True, default='', max_length=500)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('bio', models.TextField(default='')),
                ('monthly_listeners', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(default='', max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('cover_url', models.URLField(blank=True, default='', max_length=500)),
                ('audio_url', models.URLField(blank=True, default='', max_length=500)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='searchapp.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='searchapp.artist')),
            ],
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['name'], name='searchapp_a_name_790c2a_idx'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='searchapp.artist'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist'], name='searchapp_s_artist__e27160_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['album'], name='searchapp_s_album_i_d06878_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='searchapp_s_title_28e1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre'], name='searchapp_s_genre_1d13dc_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['release_year'], name='searchapp_s_release_8d3c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['artist'], name='searchapp_a_artist__131a81_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['name'], name='searchapp_a_name_8b243c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('artist', 'name')},
        ),
    ]
