# Generated by Django 4.2.17 on 2026-03-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('song_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-popularity_score'], name='searchapp_s_popular_60745d_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-release_date'], name='searchapp_s_release_f6a742_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre', '-popularity_score'], name='searchapp_s_genre_dc76aa_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='searchapp_g_name_8de89c_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['song_count'], name='searchapp_g_song_co_2c2916_idx'),
        ),
    ]
