# Generated by Django 4.2.17 on 2026-03-27 09:11

import collabapp.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.IntegerField()),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=collabapp.models.default_expires_at)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='collabapp_i_token_058d65_idx'), models.Index(fields=['playlist_id', 'is_active'], name='collabapp_i_playlis_187a74_idx')],
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['playlist_id'], name='collabapp_c_playlis_fbab4e_idx'), models.Index(fields=['user_id'], name='collabapp_c_user_id_ec37de_idx')],
                'unique_together': {('playlist_id', 'user_id')},
            },
        ),
    ]
