# Generated by Django 4.2.17 on 2026-03-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='searchapp.song')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', '-played_at'], name='historyapp__user_id_8ff536_idx'), models.Index(fields=['song', '-played_at'], name='historyapp__song_id_5c351a_idx')],
            },
        ),
    ]
