# Generated by Django 4.2.17 on 2026-03-29 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndoRedoConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('undo_window_hours', models.IntegerField(default=24)),
                ('max_actions', models.IntegerField(default=1000)),
                ('auto_cleanup', models.BooleanField(default=True)),
                ('disabled_action_types', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Undo/Redo Configuration',
                'verbose_name_plural': 'Undo/Redo Configurations',
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('action_type', models.CharField(choices=[('playlist_create', 'Create Playlist'), ('playlist_delete', 'Delete Playlist'), ('playlist_update', 'Update Playlist'), ('playlist_duplicate', 'Duplicate Playlist'), ('track_add', 'Add Track'), ('track_remove', 'Remove Track'), ('track_reorder', 'Reorder Tracks'), ('track_sort', 'Sort Tracks'), ('playlist_follow', 'Follow Playlist'), ('playlist_unfollow', 'Unfollow Playlist'), ('playlist_like', 'Like Playlist'), ('playlist_unlike', 'Unlike Playlist'), ('comment_add', 'Add Comment'), ('comment_delete', 'Delete Comment'), ('invite_generate', 'Generate Invite'), ('collaborator_add', 'Add Collaborator'), ('collaborator_remove', 'Remove Collaborator')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('before_state', models.JSONField(default=dict)),
                ('after_state', models.JSONField(default=dict)),
                ('delta', models.JSONField(default=dict)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_undone', models.BooleanField(db_index=True, default=False)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('undone_action_id', models.UUIDField(blank=True, null=True)),
                ('is_redone', models.BooleanField(default=False)),
                ('redone_at', models.DateTimeField(blank=True, null=True)),
                ('redone_action_id', models.UUIDField(blank=True, null=True)),
                ('is_undoable', models.BooleanField(default=True)),
                ('undo_deadline', models.DateTimeField(blank=True, null=True)),
                ('parent_action_id', models.UUIDField(blank=True, null=True)),
                ('related_actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='historyapp__user_id_969d24_idx'), models.Index(fields=['action_id'], name='historyapp__action__6a88cd_idx'), models.Index(fields=['is_undone'], name='historyapp__is_undo_af9f72_idx'), models.Index(fields=['entity_type', 'entity_id'], name='historyapp__entity__f6d35d_idx'), models.Index(fields=['-created_at'], name='historyapp__created_020da8_idx')],
            },
        ),
    ]
