# Generated by Django 4.2.17 on 2026-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0002_undoredoconfiguration_useraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('playlist_create', 'Create Playlist'), ('playlist_delete', 'Delete Playlist'), ('playlist_update', 'Update Playlist'), ('playlist_duplicate', 'Duplicate Playlist'), ('playlist_make_collaborative', 'Make Collaborative'), ('track_add', 'Add Track'), ('track_remove', 'Remove Track'), ('track_reorder', 'Reorder Tracks'), ('track_sort', 'Sort Tracks'), ('playlist_follow', 'Follow Playlist'), ('playlist_unfollow', 'Unfollow Playlist'), ('playlist_like', 'Like Playlist'), ('playlist_unlike', 'Unlike Playlist'), ('liked_songs_add', 'Add to Liked Songs'), ('liked_songs_remove', 'Remove from Liked Songs'), ('comment_add', 'Add Comment'), ('comment_edit', 'Edit Comment'), ('comment_delete', 'Delete Comment'), ('comment_reply', 'Reply to Comment'), ('comment_like', 'Like Comment'), ('comment_remove_like', 'Remove Like from Comment'), ('invite_generate', 'Generate Invite'), ('collaborator_add', 'Add Collaborator'), ('collaborator_remove', 'Remove Collaborator')], db_index=True, max_length=50),
        ),
    ]
