# Generated by Django 4.2.17 on 2026-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to='audio/')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('uploaded_by_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='playbackapp_title_7d379e_idx'), models.Index(fields=['uploaded_by_id'], name='playbackapp_uploade_977093_idx'), models.Index(fields=['-created_at'], name='playbackapp_created_d9f5ce_idx')],
            },
        ),
    ]
