from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    PlaylistViewSet,
    health_check,
    PlaylistStatsView,
    FeaturedPlaylistsView,
    DuplicatePlaylistView,
    BatchDeleteView,
    BatchUpdateView,
    CoverUploadView,
    CoverDeleteView,
    UserPlaylistsView,
    PlaylistFollowView,
    PlaylistLikeView,
    RecommendedPlaylistsView,
    SimilarPlaylistsView,
    AutoGeneratedPlaylistsView,
    EnhancedBatchDeleteView,
    PlaylistExportView,
    PlaylistImportView,
    PlaylistSnapshotView,
    PlaylistRestoreView,
)

router = DefaultRouter()
router.register(r"", PlaylistViewSet, basename="playlist")

urlpatterns = [
    path("health/", health_check),
    path("<int:playlist_id>/stats/", PlaylistStatsView.as_view(), name="playlist-stats"),
    path("featured/", FeaturedPlaylistsView.as_view(), name="featured-playlists"),
    # Phase 2: Core Operations
    path("<int:playlist_id>/duplicate/", DuplicatePlaylistView.as_view(), name="playlist-duplicate"),
    path("batch-delete/", BatchDeleteView.as_view(), name="batch-delete"),
    path("batch-update/", BatchUpdateView.as_view(), name="batch-update"),
    path("<int:playlist_id>/cover/", CoverUploadView.as_view(), name="cover-upload"),
    # Phase 3: Social Features
    path("users/<int:user_id>/playlists/", UserPlaylistsView.as_view(), name="user-playlists"),
    path("<int:playlist_id>/follow/", PlaylistFollowView.as_view(), name="playlist-follow"),
    path("<int:playlist_id>/like/", PlaylistLikeView.as_view(), name="playlist-like"),
    # Phase 4: Smart Features
    path("recommended/", RecommendedPlaylistsView.as_view(), name="recommended-playlists"),
    path("<int:playlist_id>/similar/", SimilarPlaylistsView.as_view(), name="similar-playlists"),
    path("auto-generated/", AutoGeneratedPlaylistsView.as_view(), name="auto-generated-playlists"),
    # Phase 5: Advanced Operations
    path("batch-delete-advanced/", EnhancedBatchDeleteView.as_view(), name="batch-delete-advanced"),
    path("import/", PlaylistImportView.as_view(), name="playlist-import"),
    path("<int:playlist_id>/export/", PlaylistExportView.as_view(), name="playlist-export"),
    path("<int:playlist_id>/snapshots/", PlaylistSnapshotView.as_view(), name="playlist-snapshots"),
    path("<int:playlist_id>/restore/<int:snapshot_id>/", PlaylistRestoreView.as_view(), name="playlist-restore"),
    path("", include(router.urls)),
]
