# Generated by Django 4.2.17 on 2026-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField(db_index=True)),
                ('following_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'User Follow',
                'verbose_name_plural': 'User Follows',
                'indexes': [models.Index(fields=['follower_id'], name='authapp_use_followe_8c710d_idx'), models.Index(fields=['following_id'], name='authapp_use_followi_07f772_idx'), models.Index(fields=['-created_at'], name='authapp_use_created_5443b2_idx')],
                'unique_together': {('follower_id', 'following_id')},
            },
        ),
    ]
