# Generated by Django 4.2.17 on 2026-03-28 13:34

from django.db import migrations, models
import shareapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.IntegerField()),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=shareapp.models.default_expires_at)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='shareapp_sh_token_ad676e_idx'), models.Index(fields=['playlist_id', 'is_active'], name='shareapp_sh_playlis_911816_idx')],
            },
        ),
    ]
