# Generated by Django 4.2.17 on 2026-04-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
