# Generated by Django 4.2.17 on 2026-03-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searchapp', '0001_initial'),
        ('playlistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by_id', models.IntegerField()),
                ('position', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='playlistapp.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='searchapp.song')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['playlist', 'position'], name='trackapp_tr_playlis_7d718c_idx'), models.Index(fields=['playlist', 'added_at'], name='trackapp_tr_playlis_d45f23_idx'), models.Index(fields=['added_by_id'], name='trackapp_tr_added_b_c2d53a_idx')],
                'unique_together': {('playlist', 'song')},
            },
        ),
    ]
