# Generated by Django 4.2.17 on 2026-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapp', '0002_usertrackhide'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['song', '-added_at'], name='trackapp_tr_song_id_d163e8_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['playlist', '-position'], name='trackapp_tr_playlis_c26b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['playlist', '-added_at'], name='trackapp_tr_playlis_0a5036_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['added_by_id', '-added_at'], name='trackapp_tr_added_b_0527d8_idx'),
        ),
    ]
