# Generated by Django 4.2.17 on 2026-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('cover_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
            ],
        ),
    ]
