# Generated by Django 4.2.17 on 2026-03-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('playlist_type', models.CharField(choices=[('solo', 'Solo'), ('collaborative', 'Collaborative')], default='solo', max_length=15)),
                ('cover_url', models.URLField(blank=True, default='', max_length=500)),
                ('max_songs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['owner_id'], name='playlistapp_owner_i_7b3407_idx'), models.Index(fields=['name'], name='playlistapp_name_13025f_idx'), models.Index(fields=['created_at'], name='playlistapp_created_4dedd1_idx'), models.Index(fields=['updated_at'], name='playlistapp_updated_d71a9c_idx'), models.Index(fields=['playlist_type'], name='playlistapp_playlis_dc44dd_idx')],
            },
        ),
    ]
