# Generated by Django 4.2.17 on 2026-03-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0002_userplaylistarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylistLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='playlistapp.playlist')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='playlistapp_user_id_48189a_idx'), models.Index(fields=['playlist'], name='playlistapp_playlis_827c4d_idx'), models.Index(fields=['liked_at'], name='playlistapp_liked_a_0f643b_idx')],
                'unique_together': {('user_id', 'playlist')},
            },
        ),
        migrations.CreateModel(
            name='UserPlaylistFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='playlistapp.playlist')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='playlistapp_user_id_69a24d_idx'), models.Index(fields=['playlist'], name='playlistapp_playlis_0b9df5_idx'), models.Index(fields=['followed_at'], name='playlistapp_followe_82bb9a_idx')],
                'unique_together': {('user_id', 'playlist')},
            },
        ),
    ]
