# Generated by Django 4.2.17 on 2026-03-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0003_userplaylistlike_userplaylistfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_data', models.JSONField()),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(blank=True, default='', max_length=255)),
                ('track_count', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='playlistapp.playlist')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['playlist'], name='playlistapp_playlis_d8ce22_idx'), models.Index(fields=['created_at'], name='playlistapp_created_fa6a79_idx'), models.Index(fields=['-created_at'], name='playlistapp_created_853490_idx')],
            },
        ),
    ]
