# Generated by Django 4.2.17 on 2026-03-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0004_playlistsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(db_index=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Playlist Comment Like',
                'verbose_name_plural': 'Playlist Comment Likes',
                'indexes': [models.Index(fields=['comment_id'], name='playlistapp_comment_b22b42_idx'), models.Index(fields=['user_id'], name='playlistapp_user_id_56166c_idx'), models.Index(fields=['-created_at'], name='playlistapp_created_e68d7b_idx')],
                'unique_together': {('comment_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.IntegerField(db_index=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('parent_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('content', models.TextField()),
                ('likes_count', models.IntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Playlist Comment',
                'verbose_name_plural': 'Playlist Comments',
                'indexes': [models.Index(fields=['playlist_id', '-created_at'], name='playlistapp_playlis_868d93_idx'), models.Index(fields=['user_id'], name='playlistapp_user_id_021d7e_idx'), models.Index(fields=['parent_id'], name='playlistapp_parent__37bbb0_idx'), models.Index(fields=['-created_at'], name='playlistapp_created_28a26e_idx')],
            },
        ),
    ]
