# Generated by Django 4.2.17 on 2026-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0005_playlistcommentlike_playlistcomment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['owner_id', '-updated_at'], name='playlistapp_owner_i_76d194_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['visibility', '-created_at'], name='playlistapp_visibil_1e8aad_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['visibility', 'playlist_type'], name='playlistapp_visibil_f5f060_idx'),
        ),
    ]
