# Generated by Django 4.2.17 on 2026-03-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0006_playlist_playlistapp_owner_i_76d194_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_liked_songs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
    ]
