# Generated by Django 4.2.17 on 2026-04-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistapp', '0007_playlist_is_liked_songs_playlist_is_system_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
